# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  ##########
  # MASTER #
  ##########
  config.vm.define "master" do |node|
    node.vm.hostname = "master.local"
    node.vm.box = "centos/7"
    node.vm.network "forwarded_port", guest: 22, host: 7022
    node.vm.provider "virtualbox" do |v|
        v.customize [ "modifyvm", :id, "--cpus", "1" ]
        v.customize [ "modifyvm", :id, "--memory", "1024" ]
	v.gui = false
    end
    node.vm.provision "shell", inline: "yum update -y && yum install vim htop tree curl wget -y"
    node.vm.provision "shell", inline: "sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config"
    node.vm.provision "shell", inline: "systemctl restart sshd"
  end
  ##########

  ###########
  # Node 1 #
  ###########
  config.vm.define "node1" do |node|
    node.vm.hostname = "node1.local"
    node.vm.box = "centos/7"
    node.vm.network "forwarded_port", guest: 22, host: 7023
    node.vm.provider "virtualbox" do |v|
        v.customize [ "modifyvm", :id, "--cpus", "2" ]
        v.customize [ "modifyvm", :id, "--memory", "2048" ]
	v.gui = false
    end
    node.vm.provision "shell", inline: "yum update -y && yum install vim htop tree curl wget -y"
    node.vm.provision "shell", inline: "sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config"
    node.vm.provision "shell", inline: "systemctl restart sshd"
  end
  ###########

  ###########
  # Node 2 #
  ###########
  config.vm.define "node2" do |node|
    node.vm.hostname = "node2.local"
    node.vm.box = "centos/7"
    node.vm.network "forwarded_port", guest: 22, host: 7024
    node.vm.provider "virtualbox" do |v|
        v.customize [ "modifyvm", :id, "--cpus", "2" ]
        v.customize [ "modifyvm", :id, "--memory", "2048" ]
	v.gui = false
    end
    node.vm.provision "shell", inline: "yum update -y && yum install vim htop tree curl wget -y"
    node.vm.provision "shell", inline: "sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config"
    node.vm.provision "shell", inline: "systemctl restart sshd"
  end
  ###########
end